### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by mmattioli**
Improvements to the markdown documentation to increase the readability and organization of the documentation as a whole. While some of the changes are in the realm of markdown styling, many are to fix various markdown rendering errors.

### CODE REVIEW

**Comment by mmattioli** [comment]
@AWSwinefred can you elaborate as to what you would like changed?

**Comment by AWSwinefred** [comment]
Hi Michael,

Thank you contributing to the aws-fpga repository. Due to quantity of changes, (~150 files) it will take time to evaluate the all changes, particularly changes to C code and scripts.

If possible, would you please resubmit your PR without any changes to the file headers? Also, if you feel there are changes that are urgent, because they affect the functionality of the developer's kit, please let us know.

Once again, thank you for your PR.

Winefred

**Comment by mmattioli** [comment]
@AWSwinefred take your time reviewing everything. I don't understand the concern about header files modifications (most of them are adjustments to comments)?

**Comment by AWSwinefred** [comment]
Can one of the admins verify this patch?

**Comment by AWSwinefred** [comment]
Can one of the admins verify this patch?

**Comment by deeppat** [comment]
Run tests

**Comment by AWSwinefred** [comment]
run tests

**Comment by mmattioli** [comment]
@deeppat @AWSwinefred when can this be merged?

**Pull request closed without merging**
