### PR TITLE
Minor code improvements

### PR DESCRIPTION
**Pull request by mmattioli**
Several `.c` and `.h` files were refactored to be more uniform and
improve overall readability and comprehension of the code within them.

### CODE REVIEW

**Comment by mmattioli** [comment]
@AWSwinefred can you elaborate as to what you would like changed?

**Comment by AWSwinefred** [comment]
Hi Michael,

Thank you contributing to the aws-fpga repository. Due to quantity of changes, (~150 files) it will take time to evaluate the all changes, particularly changes to C code and scripts.

If possible, would you please resubmit your PR without any changes to the file headers? Also, if you feel there are changes that are urgent, because they affect the functionality of the developer's kit, please let us know.

Once again, thank you for your PR.

Winefred

**Comment by mmattioli** [comment]
@AWSwinefred take your time reviewing everything. I don't understand the concern about header files modifications (most of them are adjustments to comments)?

**Comment by AWSwinefred** [comment]
Hi Michael,

Regarding the file headers, we have tools that check for the presence and the correctness of the file headers. Most of the modifications in this PR remove the first couple of lines of the header which contain the title. These lines should be left in-place.

Thanks again for your contribution.

Winefred

**Comment by AWSwinefred** [comment]
Can one of the admins verify this patch?

**Comment by AWSwinefred** [comment]
Can one of the admins verify this patch?

**Comment by mmattioli** [comment]
@AWSwinefred I just refactored and removed the modified header files as you requested.

**Comment by deeppat** [comment]
run tests

**Comment by deeppat** [comment]
Run tests

**Comment by deeppat** [comment]
Not sure why this failed. Run tests again.

**Comment by deeppat** [comment]
I think the reason is that one of the hooks didn't get handled correctly by Jenkins. Please run tests again. Hopefully for the last time 😄

**Comment by mmattioli** [comment]
@deeppat @AWSwinefred when can this be merged?

**Comment by AWSwinefred** [comment]
Thank you for making the requested changes. Since these change several C files, they require an additional level of checks for security.

**Comment by mmattioli** [comment]
@deeppat @AWSwinefred is there any update/progress?

**Comment by mmattioli** [comment]
@deeppat @AWSwinefred is there any update/progress?

**Comment by mmattioli** [comment]
@deeppat @AWSwinefred @jeffbarr @jpeddicord @bwhitman @someone is there any update/progress?

**Comment by kristopk** [comment]
Hi Michael,
Thanks for contributing to the aws-fpga project.  We appreciate your help with improving the quality of the code.  The team is focused on upcoming releases, therefore, to reduce reviews and merge conflicts with our staging repo, we need to limit the master changes.  Please remove non-critical changes like: license header edits,  adding/removing whitespaces and newline changes;  then re-submit your pull request. 
Thanks
Kris

**Pull request closed without merging**
