### PR TITLE
Add mem check to build script

### PR DESCRIPTION
**Pull request by deeppat**

### CODE REVIEW

**Comment by AWSwinefred** [comment]
Can one of the admins verify this patch?

**Comment by AWSwinefred** [comment]
Can one of the admins verify this patch?

**Comment by deeppat** [comment]
run dcp tests

**Comment by deeppat** [comment]
run dcp tests

**Comment by deeppat** [comment]
Run dcp tests

**Comment by deeppat** [comment]
run dcp tests

**Comment by deeppat** [comment]
run dcp tests

**Comment by AWSwinefred** [comment]
run tests

**Pull request merged**
