### PR TITLE
Minor script improvements

### PR DESCRIPTION
**Pull request by mmattioli**
Minor improvements to some scripts, mostly in the realm of formatting
and spacing for readability

### CODE REVIEW

**Comment by mmattioli** [comment]
@AWSwinefred can you elaborate as to what you would like changed?

**Comment by AWSwinefred** [comment]
Hi Michael,

Thank you contributing to the aws-fpga repository. Due to quantity of changes, (~150 files) it will take time to evaluate the all changes, particularly changes to C code and scripts.

If possible, would you please resubmit your PR without any changes to the file headers? Also, if you feel there are changes that are urgent, because they affect the functionality of the developer's kit, please let us know.

Once again, thank you for your PR.

Winefred

**Comment by mmattioli** [comment]
@AWSwinefred take your time reviewing everything. I don't understand the concern about header files modifications (most of them are adjustments to comments)?

**Comment by AWSwinefred** [comment]
Can one of the admins verify this patch?

**Comment by AWSwinefred** [comment]
Can one of the admins verify this patch?

**Comment by deeppat** [comment]
Run tests

**Comment by mmattioli** [comment]
@deeppat @AWSwinefred when can this be merged?

**Comment by AWSwinefred** [comment]
Thank you for your submission. This PR removes the titles from several of the files. It also modifies several scripts which will require an additional review for security reasons.

**Comment by mmattioli** [comment]
@deeppat @AWSwinefred is there any update/progress?

**Comment by mmattioli** [comment]
@deeppat @AWSwinefred is there any update/progress?

**Comment by mmattioli** [comment]
@deeppat @AWSwinefred @jeffbarr @jpeddicord @bwhitman is there any update/progress?

**Comment by kristopk** [comment]
Hi Michael,
Thanks for contributing to the aws-fpga project.  We appreciate your help with improving the quality of the code.  The team is focused on upcoming releases, therefore, to reduce reviews and merge conflicts with our staging repo, we need to limit the master changes.  Please remove non-critical changes like: license header edits and adding/removing whitespaces;  then re-submit your pull request. 
Thanks
Kris

**Pull request closed without merging**
